name: ecapa-tdnn
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=2.0.1
  - torchaudio=2.0.2
  # - cudatoolkit=11.8  # Remove this line for CPU-only version
  - fastapi=0.95.0
  - uvicorn=0.20.0
  - librosa=0.9.2
  - numpy=1.24.2
  - matplotlib=3.7.1
  - scikit-learn=1.2.2
  - seaborn=0.12.2
  - pip=23.1.2
  - pip:
      - torchvision==0.15.2  # For potential data augmentation
      - python-multipart==0.0.6  # Required for FastAPI file uploads
      - tqdm==4.65.0  # Progress bars
      - soundfile==0.12.1  # Alternative audio loading